### ISSUE TITLE
Fails when using old versions of clang-tidy

### ISSUE THREAD

**Issue by notskm** [notskm/vscode-clang-tidy#4]
At some point, the output of `clang-tidy --export-fixes=-` changed. The extension breaks when it encounters the old output. I'm working on a fix for this.

---

Old output:
``` yaml    
MainSourceFile:  /path/to/main.cpp
Diagnostics:
  - DiagnosticName:  clang-analyzer-deadcode.DeadStores
    Message: 'Value stored to ''num'' during its initialization is never read'
    FileOffset: 85
    FilePath: /path/to/main.cpp
    Replacements:
```

New output:
```yaml
MainSourceFile:  '/path/to/main.cpp'
Diagnostics:
  - DiagnosticName:  clang-analyzer-deadcode.DeadStores
    DiagnosticMessage:
      Message:         'Value stored to ''num'' during its initialization is never read'
      FilePath:        '/path/to/main.cpp'
      FileOffset:      85
      Replacements:    []
    Notes:
      - Message:         'Value stored to ''num'' during its initialization is never read'
        FilePath:        '/path/to/main.cpp'
        FileOffset:      85
        Replacements:    []
```
